print ('This marks the begining of my python journey')
print("I love Python because it's interesting")
print("Hello Worold, it is okay. happy :)")
print("So I didn't know my path and could not codE")
print("It is Okay and it can be better and better")
